variable "app_name" {}
variable "common_tags" {}
variable "environment" {}
variable "vpc_id" {}
variable "public_subnets" {}
variable "private_subnets" {}
variable "database_availability_zones" {}
variable "region" {}
variable "db_migration_sg" {}
variable "environment_full_name" {}