name: Grant Admin SSO Access to S3 KMS Key

on:
  workflow_dispatch:
    inputs:
      action:
        description: Grant or rollback access
        required: true
        type: choice
        options:
          - grant
          - rollback
      reason:
        description: Reason for access
        required: true
        type: string

permissions:
  id-token: write
  contents: write

jobs:
  apply:
    runs-on: ubuntu-latest
    # environment: prod
    steps:
      - uses: actions/checkout@v4

      - name: Edit locals file to grant or rollback access
        run: python3 .github/scripts/edit_locals.py ${{ inputs.action }}

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add root_s3_bucket_access.tf
          git commit -m "${{ inputs.action }}: KMS access - ${{ inputs.reason }}"
          git push

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.WORKFLOW_PAT }}
          aws-region: eu-west-2

      - name: Send usage message
        if: always()
        uses: nationalarchives/tdr-github-actions/.github/actions/slack-send@f318ce8a5d99c08b1235663f97fdb1b35844674e # v0.0.39
        with:
          message: "${{ github.actor }} has ${{ inputs.action }} KMS access. Reason given: ${{ inputs.reason }}"
          slack-url: ${{ secrets.SLACK_WEBHOOK }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - run: terraform init
      - run: terraform plan -target=module.s3_internal_kmy_key.aws_kms_key.encyrption -out=tfplan
      - run: terraform apply -auto-approve tfplan

        # add a slack notification that lets us know who is asking and their reason?


        # target needs to be the kms key. target the line that you want changing. couold chnge both and the target will still work. python script.
        # a script that targets that one line. might be a github actions thing out of the box. checkout to change the file.
        # want to create a branch that makes the change as part of the action. commit to that branch then run the plan and apply with a clean up. 
        # could maybe do it all in bash rather than python. inline in a github action. look at github actions that make changes to a file. 
        # clean the branch with a rollback. notify slack needs to be included. 