name: 'Terraform apply'
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'The environment to deploy against.'
        required: true
        options:
          - intg
          - staging
          - prod
        default: 'intg'
permissions:
  id-token: write
  contents: write
jobs:
  apply:
    uses: nationalarchives/tdr-github-actions/.github/workflows/terraform_apply.yml@main
    with:
      repo-name: tdr-terraform-environments
      environment: ${{ github.event.inputs.environment }}
    secrets:
      MANAGEMENT_ACCOUNT: ${{ secrets.MANAGEMENT_ACCOUNT }}
      WORKFLOW_PAT: ${{ secrets.WORKFLOW_PAT }}
      ACCOUNT_NUMBER: ${{ secrets.ACCOUNT_NUMBER }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      INTG_ACCOUNT_NUMBER: ${{ secrets.INTG_ACCOUNT_NUMBER }}
      STAGING_ACCOUNT_NUMBER: ${{ secrets.STAGING_ACCOUNT_NUMBER }}
      PROD_ACCOUNT_NUMBER: ${{ secrets.PROD_ACCOUNT_NUMBER }}
